name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.IAM_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      working-directory: tf
      run: terraform init

    - name: Terraform Plan
      working-directory: tf
      run: terraform plan

    - name: Terraform Apply
      working-directory: tf
      run: terraform apply -auto-approve
